{% set version = "1.4.3" %}

package:
  name: rios
  version: {{ version }}

source:
  hg_url: https://bitbucket.org/chchrsc/rios

build:
  number: 3
  entry_points:
    - testrios.py = rios.riostests.riostestutils:testAll
    - riosprintstats.py = rios.fileinfo:main
    - rioscalcstats.py = rios.calcstats:main

requirements:
  build:
    - python
  run:
    - python
    - numpy
    - gdal 2.2.*

test:
  imports:
    - rios

about:
  home: http://rioshome.org/
  license: GPL-3.0
  summary: 'Raster I/O simplification, a set of Python modules built on top of GDAL to simplify processing raster data, including data with Raster Attribute Tables.'

extra:
  recipe-maintainers:
    - gillins
    - danclewley
    - neilflood
