{% set version = "1.4.3" %}

package:
  name: rios
  version: {{ version }}

source:
  hg_url: https://bitbucket.org/chchrsc/rios

build:
  number: 4
  script: python setup.py install
  entry_points:
    - testrios.py = rios.riostests.riostestutils:testAll
    - riosprintstats.py = rios.fileinfo:main
    - rioscalcstats.py = rios.calcstats:main

requirements:
  build:
    - python
  run:
    - python
    - numpy
    - gdal

test:
  imports:
    - rios
  commands:
    - rioscalcstats.py -h
    - riosprintstats.py -h
    - conda inspect linkages -p $PREFIX rios  # [not win]
    - conda inspect objects -p $PREFIX rios  # [osx]

about:
  home: http://rioshome.org/
  license: GPL-3.0
  license_file: LICENSE.txt
  summary: 'Raster I/O simplification, a set of Python modules built on top of GDAL to simplify processing raster data, including data with Raster Attribute Tables.'

extra:
  recipe-maintainers:
    - gillins
    - danclewley
    - neilflood
