{% set version = "1.4.6" %}

package:
  name: rios
  version: {{ version }}

source:
  fn: rios-{{ version }}.tar.gz
  url: https://bitbucket.org/chchrsc/rios/downloads/rios-{{ version }}.tar.gz
  sha256: 6fe5ceecb1cefbcef6c67e5c015261a7db4494cb5c7239b1dc8fd6db26a5419e

build:
  number: 0
  entry_points:
    - testrios.py = rios.riostests.riostestutils:testAll
    - riosprintstats.py = rios.cmdline.riosprintstats:main
    - rioscalcstats.py = rios.cmdline.rioscalcstats:main

requirements:
  build:
    - python
  run:
    - python
    - numpy
    - gdal

test:
  imports:
    - rios
  commands:
    - testrios.py
    - rioscalcstats.py -h
    - riosprintstats.py -h
    - conda inspect linkages -p $PREFIX rios  # [not win]
    - conda inspect objects -p $PREFIX rios  # [osx]

about:
  home: http://rioshome.org/
  license: GPL-3.0
  license_file: LICENSE.txt
  summary: 'Raster I/O simplification, a set of Python modules built on top of GDAL to simplify processing raster data, including data with Raster Attribute Tables.'

extra:
  recipe-maintainers: {gillins, danclewley, neilflood}
