{% set version = "1.4.4" %}

package:
  name: rios
  version: {{ version }}

source:
  fn: rios-{{ version }}.tar.gz
  url: https://bitbucket.org/chchrsc/rios/downloads/rios-{{ version }}.tar.gz
  sha256: 59fc71a3cfdc2c6de47fd38bc999bdb6de48ce882c5a680dac97118bf86b486f

build:
  number: 0
  script: python setup.py install
  entry_points:
    - testrios.py = rios.riostests.riostestutils:testAll
    - riosprintstats.py = rios.cmdline.riosprintstats:main
    - rioscalcstats.py = rios.cmdline.rioscalcstats:main

requirements:
  build:
    - python
  run:
    - python
    - numpy
    - gdal

test:
  imports:
    - rios
  commands:
    - rioscalcstats.py -h
    - riosprintstats.py -h
    - conda inspect linkages -p $PREFIX rios  # [not win]
    - conda inspect objects -p $PREFIX rios  # [osx]

about:
  home: http://rioshome.org/
  license: GPL-3.0
  license_file: LICENSE.txt
  summary: 'Raster I/O simplification, a set of Python modules built on top of GDAL to simplify processing raster data, including data with Raster Attribute Tables.'

extra:
  recipe-maintainers:
    - gillins
    - danclewley
    - neilflood
