{% set version = "2.0.2" %}

package:
  name: rios
  version: {{ version }}

source:
  fn: rios-{{ version }}.tar.gz
  url: https://github.com/ubarsc/rios/releases/download/rios-{{ version }}/rios-{{ version }}.tar.gz
  sha256: c5949f581fd6657e3257c69b382971ce5831a403a2edc8971b61197bdc78e5a4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - testrios = rios.riostests.riostestutils:testAll
    - riosprintstats = rios.cmdline.riosprintstats:main
    - rioscalcstats = rios.cmdline.rioscalcstats:main
    - rios_computeworker = rios.cmdline.rios_computeworker:mainCmd

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
  run:
    - python >=3.6
    - numpy
    - gdal
    - cloudpickle

test:
  imports:
    - rios
  commands:
    - testrios
    - rioscalcstats -h
    - riosprintstats -h
    - rios_computeworker -h

about:
  home: http://www.rioshome.org
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Raster I/O simplification, a set of Python modules built on top of GDAL to simplify processing raster data, including data with Raster Attribute Tables.

extra:
  recipe-maintainers:
    - gillins
    - danclewley
    - neilflood
