{% set version = "1.4.13" %}

package:
  name: rios
  version: {{ version }}

source:
  fn: rios-{{ version }}.tar.gz
  url: https://github.com/ubarsc/rios/releases/download/rios-{{ version }}/rios-{{ version }}.tar.gz
  sha256: 9f99f41f20ce769101e61bc8347aa96718e6e5ac37ccb47cb3e555dc4ca83427
  patches:
    # Don't install the command line progs, use entry point instead
    # Setting the env vars doesn't work for noarch packages.
    - nocmdline.patch

build:
  noarch: python
  number: 1
  script:
    - pip install .
  entry_points:
    - testrios.py = rios.riostests.riostestutils:testAll
    - riosprintstats.py = rios.cmdline.riosprintstats:main
    - rioscalcstats.py = rios.cmdline.rioscalcstats:main

requirements:
  host:
    - python >=3.6
    - setuptools
    - numpy
  run:
    - python >=3.6
    - numpy
    - gdal

test:
  imports:
    - rios
  commands:
    - testrios.py
    - rioscalcstats.py -h
    - riosprintstats.py -h

about:
  home: http://www.rioshome.org
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Raster I/O simplification, a set of Python modules built on top of GDAL to simplify processing raster data, including data with Raster Attribute Tables.

extra:
  recipe-maintainers:
    - gillins
    - danclewley
    - neilflood
