{% set version = "1.4.3" %}

package:
    name: rios
    version: {{ version }}

source:
    fn: rios-{{ version }}.tar.gz
    url: https://bitbucket.org/chchrsc/rios/downloads/rios-{{ version }}.tar.gz
    md5: c6d370262a2630ef81deb53b88e5d184

build:
    number: 0
    script: python setup.py install

requirements:
  build:
    - python
    - numpy
    - gdal
  run:
    - python
    - numpy
    - gdal

test:
    imports:
        - rios
    
about:
    home: http://rioshome.org/
    license: GPLv3
    summary: Raster I/O simplification, a set of Python modules built on top of GDAL to simplify processing raster data, including data with Raster Attribute Tables.

extra:
    recipe-maintainers:
        - gillins
