{% set version = "2.0.1" %}

package:
  name: rios
  version: {{ version }}

source:
  fn: rios-{{ version }}.tar.gz
  url: https://github.com/ubarsc/rios/releases/download/rios-{{ version }}/rios-{{ version }}.tar.gz
  sha256: 8b8bcbf11a45af46d25b95d9d4a402ec0466ed117b3464f4226a6a466d9687b5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - testrios = rios.riostests.riostestutils:testAll
    - riosprintstats = rios.cmdline.riosprintstats:main
    - rioscalcstats = rios.cmdline.rioscalcstats:main

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
  run:
    - python >=3.6
    - numpy
    - gdal
    - cloudpickle

test:
  imports:
    - rios
  commands:
    - testrios
    - rioscalcstats.py -h
    - rioscalcstats -h
    - riosprintstats.py -h
    - riosprintstats -h

about:
  home: http://www.rioshome.org
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Raster I/O simplification, a set of Python modules built on top of GDAL to simplify processing raster data, including data with Raster Attribute Tables.

extra:
  recipe-maintainers:
    - gillins
    - danclewley
    - neilflood
