travis:
  secure:
    BINSTAR_TOKEN: OfnqKXdxjgmUIhX8vltUyqowp5VskpUHELMaCrvdPvWJDps9cKI3piT0tVuc8t9dmhDT3UdlLL7Cz49qcNU/74AgIQ/jzBozFfhqMGww2dX9XsXnjAjnqOHObLqw3h7wnXpSyX5OyqC7xoFl/5r0Xy4js2KkDDT1QzlMJII4omnfa7I3KVUHZWI7HrETHQfrjjzqLsx4z7r705ssO2R14HPtjIiC65l94Ypde3XD7I0sRs3MfjgcLxC+2+6egplymR6cUNYc0ppFD8vE+zqEhZ4Rs58oVFfh2WFr/RPkn7KeT8Z+YcvYfKVn9t+UoduGum5sdJFDa7v17v8A9qA9B0ys0pCvR2VhnBJPUn7NPz/9hpM4yOlEOhqLXZaCcmI0VoJlzU6qYhJDeCy2qP7FR1JjinSMO0urzk9xgYrZGwVVxHiWF+JO5Qev2ZXWb54o61OgT0V6fUnPv4kiFJY7A/IbwRXyZUYSYoUf5nzG70UkMRsnKF/7zBzgmYz7M8xFbZSy/FZp4GpEHp1c4lw0lFtQYwC5XfaRq6G5qmWbAYEOb4U/CwqzRmINzM13fp58c1khKXkUR75X1wBDRkxJv2Hqo+cwNFd4OlNahh0XL9CzcZx0PkW+e1pJCtH2XZolrIU/gXLGg9H80ZBSRpFtjnSmLRI85WS00eFzUZZPVLg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
