appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: rJxFnQkfvRBj04Iv6p6u1scbKMKMSLFJ12Df8/orxRM1E2e+GATINxLN6w6xDaqt0kcTDwHb2H6u1mFwtxwDiFn7mX9g0C6FX6WJwtK3Ue8GoZKVGJpEMdj9TNA0qLBC9wXAink2O3CU57cfvCvCyokX4gcei3joNWP6uHJMc5xE2q0FI1zWAL8bJ9iCbO3zMUIN6406CphznpPu2gvHr0eNQIvN4Gu8A3tqYOxkzRnbx0FYtmcIwM5zwMf3ZeqpV1rA53DTLxOJqrou896l1TRgDdTlUqRC/ePWj8sY4ha4VNHcNQosmKg+/jvuNPzGWy82nc4LR34iCXzrSFmNIGKpSmBd2GRGplGB+8JThHy9pZfna0JocQD7CXdTmAOPF7oFUsLF7ihf/347jfyskiT49YhR+2ROhZ7unL9IjkuwiZeipJ6AFWBEzwTOfx7AmDFXR/fxuaLqFq4dpXgZGwq7kSewRDze/Xt4fJx6lWQBFw56exm9muz8hxyZ7bM6aFs9/xfyIVDB/71jDvwenosJ2ipis845aHGxL3t7xodODAIFd1ejziahyFrvwwDnYWuE+UkbEcyf+OAEVvsHJEuAwYwx8a1t/PCFrs2nncXD/AqX7PdL6sLguiG9uqPtBGnkvUaHG54eWZRYN5r0O+J4wYdiMqxouyRHioncjbI=}
